kind: pipeline
type: kubernetes
name: default

steps:
- name: build & push  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    create_repository: true
    region: 
      from_secret: AWS_REGION
    dockerfile: Dockerfile
    context: .
    tags: ${DRONE_COMMIT_SHA}
    repo: node-server-demo
    registry:
      from_secret: AWS_REGISTRY
    lifecycle_policy: aws-ecr-lifecycle-policy.json

- name: update-IAS  
  image: bitnami/git:2.42.0-debian-11-r45 
  environment:
    GITOPS_REPO:
      from_secret: GITOPS_REPO
    ECR_ADDR: 
      from_secret: ECR_ADDR
    GITOPS_FOLDER_NAME: 
      from_secret: GITOPS_FOLDER_NAME
    PATH:
      from_secret: PATH
  commands:
  - cd /tmp
  - git clone $GITOPS_REPO
  - cd /tmp/$GITOPS_FOLDER_NAME/
  - sed -i "s|$ECR_ADDR/${DRONE_REPO}:[^ ]*|$ECR_ADDR/${DRONE_REPO}:${DRONE_COMMIT_SHA}|g" /tmp/$GITOPS_FOLDER_NAME/$PATH/${DRONE_REPO}.yaml
  - git add -A
  - git commit -m"Drone | updated airline-engine-db2scraper image tag to ${DRONE_COMMIT_SHA}"
  - git push origin dev




    





# git clone https://tuhin37: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@github.com/tuhin37/finkraft-gitops.git

# volumes:
# - name: docker-socket  
#   host:
#     path: /var/run/docker.sock  