kind: pipeline
type: kubernetes
name: default

steps:
- name: build & push  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    create_repository: true
    region: 
      from_secret: AWS_REGION
    dockerfile: Dockerfile
    context: .
    tags: ${DRONE_COMMIT_SHA}
    repo: demo-backend
    registry:
      from_secret: AWS_REGISTRY
    lifecycle_policy: aws-ecr-lifecycle-policy.json


- name: update-IAS  
  image: bitnami/git:2.41.0-debian-11-r4 
  environment:
    GITOPS_REPO:
      from_secret: GITOPS_REPO 
    GITOPS_FOLDER:
      from_secret: GITOPS_FOLDER_NAME
    ECR_ADDR:
      from_secret: ECR_ADDR
    GIT_BRANCH: main  
  commands:
  - cd /tmp
  - git clone -b $GIT_BRANCH $GITOPS_REPO
  - cd /tmp/$GITOPS_FOLDER/
  - sed -i "s|$ECR_ADDR/node-server-demo:[^ ]*|$ECR_ADDR/node-server-demo:${DRONE_COMMIT_SHA}|g" /tmp/$GITOPS_FOLDER/demo-app/backend.yaml
  - git add -A
  - git commit -m"Drone | updated airline-engine-db2scraper image tag to ${DRONE_COMMIT_SHA}"
  - git push origin $GIT_BRANCH




    





# git clone https://tuhin37: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@github.com/tuhin37/finkraft-gitops.git

# volumes:
# - name: docker-socket  
#   host:
#     path: /var/run/docker.sock  