kind: pipeline
type: kubernetes
name: default

trigger:
  branch: 
  - main # <---------------------- user configurable

steps:
- name: build & push  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    create_repository: true
    region: 
      from_secret: AWS_REGION
    dockerfile: Dockerfile
    context: .
    tags: ${DRONE_COMMIT_SHA}
    repo: ${DRONE_REPO##*/}
    registry:
      from_secret: AWS_REGISTRY
    lifecycle_policy: aws-ecr-lifecycle-policy.json


- name: clair
  image: jmccann/drone-clair:1
  settings:
    url: http://af7ec398c88c74061b19f8dc9c81b7e6-891067631.ap-south-1.elb.amazonaws.com:6060
    username: 
    password: 
    scan_image: python:2.7


- name: update-IAS  
  image: bitnami/git:2.41.0-debian-11-r4 
  environment:
    GIT_BRANCH: main  # <---------------------- user configurable
    GITOPS_REPO:
      from_secret: GITOPS_REPO 
    GITOPS_FOLDER:
      from_secret: GITOPS_FOLDER_NAME
    ECR_ADDR:
      from_secret: ECR_ADDR
    APP_PATH:
      from_secret: APP_PATH

  commands:
  - echo ${DRONE_REPO##*/}
  - cd /tmp
  - git clone -b $GIT_BRANCH $GITOPS_REPO
  - cd /tmp/$GITOPS_FOLDER/
  - sed -i "s|$ECR_ADDR/${DRONE_REPO##*/}:[^ ]*|$ECR_ADDR/${DRONE_REPO##*/}:${DRONE_COMMIT_SHA}|g" /tmp/$GITOPS_FOLDER/$APP_PATH/${DRONE_REPO##*/}.yaml
  - git add -A
  - git commit -m"Drone | updated $APP_PATH/${DRONE_REPO##*/}.yaml with new image tag set to ${DRONE_COMMIT_SHA}"
  - git push origin $GIT_BRANCH




    





# git clone https://tuhin37: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@github.com/tuhin37/finkraft-gitops.git

# volumes:
# - name: docker-socket  
#   host:
#     path: /var/run/docker.sock  